baseURL = "http://manuelr.me"
title = "ManuelR"
theme = "paper"
author = "Manuel Ramos"
paginate = 10

[params]
    # color style
    color = 'linen'             # linen, wheat, gray, light

    # header social icons
    github = 'manuelramos'       # github.com/YOUR_GITHUB_ID
    rss = true                      # show rss icon with link

    # home page profile
    avatar = 'https://deno.land/logo.svg'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Manuel Ramos'
    bio = 'Software Developer'

    # misc
    disableHLJS = true              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon

