version: "3"
services:
  app:
    container_name: jekyll
    build:
      context: .
      dockerfile: Dockerfile
    command: jekyll serve --incremental --livereload --force_polling
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729