version: "3"

services:
  app:
    image: jekyll/jekyll:latest
    container_name: jekyll
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
    command: jekyll serve --incremental --livereload --force_polling