name: Pelican Build and Deploy

on:
  push:
    branches:
      - main # change to the name of your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pelican and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: Build site
      run: |
        pelican content -o output -s pelicanconf.py -d

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
